### PR TITLE
Numerous additions (inheritance, JSDocs comments, interfaces, type narrowing, ...)

### PR DESCRIPTION
**Pull request by cmidgley**
Here's the new round of work we've been discussing - it has a bunch of changes, and while I have done basic testing (TS only), it has not gone through the ringer yet.  Thought I'd start the discussion around the feature changes in advance of final testing and merging.

Primary changes:

1) Support for inheritance using `struct SubClass : BaseClass`, including multiple levels of inheritance.  Adjusts the constructors to accept subclass `ArrayBuffers` and manage the different offsets and lengths accordingly.  

2) Adjustments to `toJSON` and `from` to support inheritance and improved TypeScript typing.

3) Addition of new `interface` for each `class` that `Omits<...>` the extra members like `DataView`, and use that interface on `from` to provide hard typing with the defined members of the struct (avoid TS errors, enables Intellisense and allows type narrowing to work).

4) Allow empty structs to be defined, as these are needed to use type narrowing.  Cleaned up output so than when used, they generate very little overhead.  See `TypeTwo` in `example.cdv.h` for a typical use case.

5) Implement two new pragmas, `inject` and `injectInterface`, to inject any content into the output stream.  `Inject` inserts the content at the current location in the stream, whereas `injectInterface` adds the content into the classes interface definition.  See the example and readme for how this is used.

6) Extended comments so that JSDoc/TSDoc style comments (`/** ... */`) are duplicated across all getters/setters.  This provides for IDE comments to appear when looking at any property.  Regular comments (`/* ... */`) do not get duplicated.

### CODE REVIEW

**Comment by cmidgley** [comment]
Additional changes:

* Supports setting enum size with `enum MyEnum : uint8_t` style syntax.
* All exports moved to end of file (conditional on `pragma export`, with a bit of fancy formatting on the export lines).
* Added new macros, similar to `__COMPILEDATAVIEW__` for language and platform (e.g. `__LANGUAGE_TYPESCRIPT__`).
* JSDoc comments supported on enum members.
* Minor change to `output.add` to not include a blank line.
* Several bug fixes.

For the new macros, I was torn between using `__LANGUAGE__` and then doing a comparison, such as:

```c
#if __LANGUAGE__ == "typescript"
```

vs. a boolean / defined, which is what I ended up with:

```c
#if defined(__LANGUAGE_TYPESCRIPT__)
```

I ended up here because I felt it was safer in that it was obvious it would all be uppercase syntax.  Technically we could do a case-insensitive compare and avoid that issue, but that would be inconsistent with C/C++.  It's really easy to change if you prefer we use `__LANGUAGE__` (or perhaps both).

**Comment by cmidgley** [comment]
Fixed an issue where jsdoc comments were not being rendered in front of both the `interface` and the `class` (required for intellisense).

**Comment by phoddie** [comment]
I spent a bunch of time trying the changes, reading through your notes, and reviewing the generated code. I didn't get to read the changes in detail yet. I understand and agree with most of it. I have a few observations / questions.

The inheritance feature is very nice. It solves several problems while staying within the bounds of C (well.... C++). The generated constructor is perhaps more complex than needed. Here's the output:

```js
class BaseLiteral extends DataView {
   constructor(data, offset, length) {
      super(data ?? new ArrayBuffer(1), offset ?? 0, length ?? 1)
   }
}

class TypeOne extends BaseLiteral {
   constructor(data, offset, length) {
      super(data ?? new ArrayBuffer(5), offset ?? 0, length ?? 5)
   }
}
```

I don't think the subclasses (`TypeOne`) need to ever allocate the `ArrayBuffer` since the base class (`BaseLiteral`) does.  Maybe something like this:

```js
class BaseLiteral extends DataView {
   constructor(data, offset = 0, length = 1) {
      super(data ?? new ArrayBuffer(offset + length), offset, length)
   }
}

class TypeOne extends BaseLiteral {
   constructor(data, offset = 0, length = 5) {
      super(data, offset, length)
   }
}
```

For `from` with inheritance the output is:

```js
class Base extends DataView {
   static from(obj, data) {
      const result = data ?? new Base;
      if ("b1" in obj) result.b1 = obj.b1;
      if ("b2" in obj) result.b2 = obj.b2;
      return result;
   }
}

class ExtBase extends Base {
   static from(obj, data) {
      const result = super.from(obj, data ?? new ExtBase);
      if ("eb1" in obj) result.eb1 = obj.eb1;
      return result;
   }
}
```

The `Base` class should be able to instantiate the correct class directly, which eliminates the need for the `data` argument:

```js
class Base extends DataView {
   static from(obj) {
      const result = new this.constructor;
      if ("b1" in obj) result.b1 = obj.b1;
      if ("b2" in obj) result.b2 = obj.b2;
      return result;
   }
}

class ExtBase extends Base {
   static from(obj) {
      const result = super.from(obj);
      if ("eb1" in obj) result.eb1 = obj.eb1;
      return result;
   }
}
```

In the following, it is perfect (and impressive) that `eb1` ends up at offset 6 while `Base` has a size of 5.

```c
struct Base {
   uint32_t b1;
   char b2;
};

struct ExtBase : Base {
   uint16_t eb1;
};
```

```js
class Base extends DataView {
   constructor(data, offset, length) {
      super(data ?? new ArrayBuffer(5), offset ?? 0, length ?? 5)
   }
   get b1() {
      return this.getUint32(0, true);
   }
   get b2() {
      return String.fromCharCode(this.getUint8(4));
   }
}

class ExtBase extends Base {
   constructor(data, offset, length) {
      super(data ?? new ArrayBuffer(13), offset ?? 0, length ?? 13)
   }
   get eb1() {
      return this.getUint16(6, true);
   }
}
```

But, the size of `ExtBase` should be 8 bytes, but it is 13?

To try to answer your  question about the `___LANGUAGE__` or `__LANGUAGE_TYPESCRIPT__`, I looked at the `language` pragma:

```c
#pragma language(typescript)
#pragma language(typescript/node)
```

It would be nice for those to be consistent. The string compare you show (`__LANGUAGE__ == "typescript"`) is clear but not standard C. That leaves the second form as the only option. What to do with the `/node` part then? Maybe nothing for now and we don't allow conditionals on the runtime part of the language specification? Otherwise, to follow the style would require also defining either `__LANGUAGE__TYPESCRIPT_NODE__` or `__RUNTIME__NODE__`.  I prefer the latter since it applies independent of language.

I think I understand what you are doing with the inject features. The `injectInterface` is really only for TypeScript: "interface" as a concept doesn't exist in JavaScript and the injected code for JavaScriptis put outside the generated class body(!). Since it is just for TypeScript, perhaps it should only generate output if the language is TypeScript. That eliminates the need to check the language around it. 

I almost think you could just have `inject` (no `injectInterface`) and only use it for TypeScript. If it is inside the struct, it goes in the interface.

**Comment by cmidgley** [comment]
I'm working through this now.  The first point about simplifying the constructors on inheritance is done.

The second point you say:

>The Base class should be able to instantiate the correct class directly, which eliminates the need for the data argument:

```js
class Base extends DataView {
   static from(obj) {
      const result = new this.constructor;
      if ("b1" in obj) result.b1 = obj.b1;
      if ("b2" in obj) result.b2 = obj.b2;
      return result;
   }
}

class ExtBase extends Base {
   static from(obj) {
      const result = super.from(obj);
      if ("eb1" in obj) result.eb1 = obj.eb1;
      return result;
   }
}
```

On this one, I'm a bit confused on how `this` works.  It could be one of those weird JS things, but `from` is static, so I don't see how `this.constructor` will work, nor will it follow the inheritance chain to perform the correct constructor.  

On the allocation size, that's clearly wrong - I've yet to debug it.

For the macros on language and platform, I have both `__LANGUAGE__` and `__PLATFORM__` so you can mix and match.  It's working, so perhaps live it alone?

The pragma `injectInterface` does only inject when it is TypeScript, and the `readme` already has that documented.  I removed the `#if` from the example file, as that perhaps was misleading and for sure unnecessary. `inject` does not work for the typescript `injectInterface` use case (at least not easily) as the injection generation brings all all the member types as well.

**Comment by cmidgley** [comment]
Latest update reflects the fix for size and improved constructors (plus cleaned up example).  Still pending discussion is `from`.  I also found/fixed a TypeScript issue with the generated interface when using inheritance.

**Comment by phoddie** [comment]
Hey, @cmidgley, thanks going through this.

On the constructors, I mistakenly assumed that `from` is an instance method rather than a static method. The basic idea still works, but the details are different (yes, more JavaScript `this` obscura):

```js
class Base {
	base = true;
	static from(obj) {
		return new this.prototype.constructor;
	}
}

class ExtendsBase extends Base {
	extendsBase = true;
	static from(obj) {
		return super.from();
	}
}
```
> For the macros on language and platform, I have both __LANGUAGE__ and __PLATFORM__ so you can mix and match. It's working, so perhaps let it alone?

Seems reasonable. I can imagine coming back to this when we know more.

> The pragma injectInterface does only inject when it is TypeScript, and the readme already has that documented. I removed the #if from the example file, as that perhaps was misleading and for sure unnecessary. inject does not work for the typescript injectInterface use case (at least not easily) as the injection generation brings all all the member types as well.

`injectInterface` is active in the PR I reviewed when the language is JavaScript, which is how I stumbled over it (explore first, read the docs later!).

> inject does not work for the typescript injectInterface use case (at least not easily) as the injection generation brings all all the member types as well.

I understand that the behavior is different based on the context. Since the pragma knows the context, it can modify its behavior. This is an tricky feature to support a special situation. I don't think we know enough to try to generalize yet, so a single pragma that gives the behavior you want seems like the right place to start.

**Comment by cmidgley** [comment]
> `injectInterface` is active in the PR`

I think the code has always had a `if ("typescript" == language)` condition around it's injection.  It's always active, in that you can always set the pragma, but it doesn't do anything unless it's typescript.  If I'm wrong about that, perhaps point me to the source?

I'm working on `from` now.  Using `new this.prototype.constructor()` make TypeScript unhappy, but my tests so far are showing that just `new this()` works in the static method on both JS and TS.  If you feel otherwise, chime in!  Should have that update shortly.

**Comment by phoddie** [comment]
> I think the code has always had a if ("typescript" == language) condition around it's injection. It's always active, in that you can always set the pragma, but it doesn't do anything unless it's typescript. If I'm wrong about that...

I didn't try to read that code. I just grabbed the sources and experimented in the browser. I can try again on the next round so you don't need to spend more time on this.

> ...my tests so far are showing that just new this() works in the static method on both JS and TS. 

Yes, that should work too. Nice improvement.

**Comment by cmidgley** [comment]
`from` implemented hopefully as discussed.  No runtime testing yet (just static analysis, like lint/ts passing).

**Comment by phoddie** [comment]
Thanks for the updates. It looks good. I've merged the changes.

More testing would be good. That's a lot of changes.

Just a few  notes:
- I did some code changes mostly for style and concision. That should help me, at least, in maintaining the code.
- Renamed `includeSource` to `outputSource` to be consistent with `outputByteLength`.
- Some documentation edits, mostly to reflect the change in how `export` is generated
- I couldn't understand `inject` and `injectInterface` well enough to be comfortable yet. I commented them out in the documentation but left the implementation. I'm sure we'll come back to that.

------

FWW – here's an example of `inject` behaving strangely with JavaScript output:

```c
struct Integers {
   #pragma inject(x = 12)
   uint16_t size;
};
```

```js
   x = 12;
class Integers extends DataView {
   constructor(data, offset = 0, length = 2) {
      super(data ?? new ArrayBuffer(offset + length), offset, length)
      ...
```

**Comment by cmidgley** [comment]
Thanks for merging and being willing to accept so many changes (including keeping `inject` and `injectInterface` as private for now).

I'm glad to review and adjust `inject`/`injectInterface`.  The issue you show with inject moving above the class is a side effect of parsing where members are parsed and cached before the class is output (thereby avoiding two passes).  If we want inject to work within `struct` we will need to work around the "look ahead" system that is used when parsing members.  I had a similar issue with comments, so it's certainly possible.  Even with comment there are edge cases, as comments that precede members are attached to the member (only one comment is retained) which means comments after the last member are lost.  That might become a bigger issue if `inject` becomes useful, warranting some amount of refactoring so we get more consistency in the parse vs. generation flow.

**Comment by phoddie** [comment]
Thanks for the contributions! The subclassing support is particularly great, both because of the functionality it provides and for doing so with completely standard syntax.

I think of `inject`/`injectInterface` as experimental. There's something there, but I'm not sure we have found the optimal syntax and definition .

**Pull request merged**
